//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 6.0.42.1140
//     Runtime Version: 4.0.30319.17929
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace Beta.Resources;

interface

uses
    System;
    
type
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '4.0.0.0')]
    [System.Diagnostics.DebuggerNonUserCodeAttribute]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    AppResources = public class
    private 
        class var resourceMan: System.Resources.ResourceManager;
        class var resourceCulture: System.Globalization.CultureInfo;
        class method get_ResourceManager: System.Resources.ResourceManager;
        class method get_Culture: System.Globalization.CultureInfo;
        class method set_Culture(value: System.Globalization.CultureInfo);
        class method get_AppBarButtonText: System.String;
        class method get_AppBarMenuItemText: System.String;
        class method get_ApplicationTitle: System.String;
        class method get_ResourceFlowDirection: System.String;
        class method get_ResourceLanguage: System.String;
        class method get_SampleProperty: System.String;
    assembly 
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
        constructor;
    public
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property ResourceManager: System.Resources.ResourceManager read get_ResourceManager;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property Culture: System.Globalization.CultureInfo read get_Culture write set_Culture;
        class property AppBarButtonText: System.String read get_AppBarButtonText;
        class property AppBarMenuItemText: System.String read get_AppBarMenuItemText;
        class property ApplicationTitle: System.String read get_ApplicationTitle;
        class property ResourceFlowDirection: System.String read get_ResourceFlowDirection;
        class property ResourceLanguage: System.String read get_ResourceLanguage;
        class property SampleProperty: System.String read get_SampleProperty;
    end;
    
implementation

{ AppResources }

constructor AppResources;
begin
end;

class method AppResources.get_ResourceManager: System.Resources.ResourceManager;
begin
    if System.Object.ReferenceEquals(resourceMan, nil) then begin
        var temp: System.Resources.ResourceManager := new System.Resources.ResourceManager('Beta.Resources.AppResources', typeOf(AppResources).Assembly);
        resourceMan := temp;
    end;
    exit(resourceMan);
end;

class method AppResources.get_Culture: System.Globalization.CultureInfo;
begin
    exit(resourceCulture);
end;

class method AppResources.set_Culture(value: System.Globalization.CultureInfo);
begin
    resourceCulture := value;
end;

class method AppResources.get_AppBarButtonText: System.String;
begin
    exit(ResourceManager.GetString('AppBarButtonText', resourceCulture));
end;

class method AppResources.get_AppBarMenuItemText: System.String;
begin
    exit(ResourceManager.GetString('AppBarMenuItemText', resourceCulture));
end;

class method AppResources.get_ApplicationTitle: System.String;
begin
    exit(ResourceManager.GetString('ApplicationTitle', resourceCulture));
end;

class method AppResources.get_ResourceFlowDirection: System.String;
begin
    exit(ResourceManager.GetString('ResourceFlowDirection', resourceCulture));
end;

class method AppResources.get_ResourceLanguage: System.String;
begin
    exit(ResourceManager.GetString('ResourceLanguage', resourceCulture));
end;

class method AppResources.get_SampleProperty: System.String;
begin
    exit(ResourceManager.GetString('SampleProperty', resourceCulture));
end;

end.
