//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.18033
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace BetaServer.Properties;

interface

type
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute('Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator', '11.0.0.0')]
    Settings = partial sealed class(System.Configuration.ApplicationSettingsBase)
    private 
        class var defaultInstance: Settings := (System.Configuration.ApplicationSettingsBase.Synchronized(new Settings()) as Settings);
        class method get_Default: Settings;
        method get_ReferenceUsername: System.String;
        method set_ReferenceUsername(value: System.String);
        method get_ReferenceUserToken: System.String;
        method set_ReferenceUserToken(value: System.String);
        method get_DownloadInfoURL: System.String;
        method set_DownloadInfoURL(value: System.String);
        method get_ServerPort: System.Int32;
        method set_ServerPort(value: System.Int32);
    public 
        class property &Default: Settings read get_Default;
        [System.Configuration.UserScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('mh')]
        property ReferenceUsername: System.String read get_ReferenceUsername write set_ReferenceUsername;
        [System.Configuration.UserScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('BADTOKEN')]
        property ReferenceUserToken: System.String read get_ReferenceUserToken write set_ReferenceUserToken;
        [System.Configuration.UserScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('https://secure.remobjects.com/api/downloads?name={0}&token={1}&appid={2}&clientid={3}')]
        property DownloadInfoURL: System.String read get_DownloadInfoURL write set_DownloadInfoURL;
        [System.Configuration.UserScopedSettingAttribute]
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Configuration.DefaultSettingValueAttribute('8098')]
        property ServerPort: System.Int32 read get_ServerPort write set_ServerPort;
    end;
    
implementation

{ Settings }

class method Settings.get_Default: Settings;
begin
    exit(defaultInstance);
end;

method Settings.get_ReferenceUsername: System.String;
begin
    exit((self['ReferenceUsername'] as System.String));
end;

method Settings.set_ReferenceUsername(value: System.String);
begin
    self['ReferenceUsername'] := value;
end;

method Settings.get_ReferenceUserToken: System.String;
begin
    exit((self['ReferenceUserToken'] as System.String));
end;

method Settings.set_ReferenceUserToken(value: System.String);
begin
    self['ReferenceUserToken'] := value;
end;

method Settings.get_DownloadInfoURL: System.String;
begin
    exit((self['DownloadInfoURL'] as System.String));
end;

method Settings.set_DownloadInfoURL(value: System.String);
begin
    self['DownloadInfoURL'] := value;
end;

method Settings.get_ServerPort: System.Int32;
begin
    exit((self['ServerPort'] as System.Int32));
end;

method Settings.set_ServerPort(value: System.Int32);
begin
    self['ServerPort'] := value;
end;

end.
